# Generated by Django 5.1.7 on 2025-03-27 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("course_title", models.TextField()),
                ("category", models.TextField()),
                ("school_name", models.TextField()),
                (
                    "description",
                    models.TextField(default="Course description coming soon!"),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("available_until", models.DateField()),
                ("author", models.TextField()),
                ("post_date", models.DateTimeField(auto_now_add=True)),
                ("is_enrolled", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Course",
                "verbose_name_plural": "Courses",
                "db_table": "course_list",
            },
        ),
    ]
