# Generated by Django 5.1.7 on 2025-03-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_course", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="is_enrolled",
            new_name="enroll_now",
        ),
        migrations.AlterField(
            model_name="course",
            name="author",
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name="course",
            name="category",
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name="course",
            name="course_title",
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name="course",
            name="school_name",
            field=models.TextField(max_length=150),
        ),
    ]
