# Generated by Django 5.1.7 on 2025-03-28 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("my_course", "0003_course_students"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="enroll_now",
        ),
    ]
